# Generated by Django 4.2 on 2023-12-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapps', '0002_course_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
