# Generated by Django 4.2 on 2023-12-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapps', '0004_material_remove_order_materials_provide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
